## SHREE KRISHNA KANTH S
## 225229136
## PDL LAB 02

### Part-I: Design OR gate using the concept of Perceptron

### Step1:

In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
def sigmoid(x):
    s=1/(1+math.exp(-x))
    return s

In [3]:
def logic_gate(w1,w2,b):
    return lambda x1,x2: sigmoid(w1*x1+w2*x2+b)

In [4]:
def test(gate):
    for a,b in (0,0),(0,1),(1,0),(1,1):
        print("{},{}: {}".format(a,b,np.round(gate(a,b))))

### Step2:

In [5]:
or_gate = logic_gate(20, 20, -10)
test(or_gate)

0,0: 0.0
0,1: 1.0
1,0: 1.0
1,1: 1.0


## Part-II: 

### Step1:

In [6]:
and_gate = logic_gate(10, 10, -10)
test(and_gate)

0,0: 0.0
0,1: 0.0
1,0: 0.0
1,1: 1.0


### Step2:

In [7]:
nor_gate = logic_gate(-20,-20,10)
test(nor_gate)

0,0: 1.0
0,1: 0.0
1,0: 0.0
1,1: 0.0


### Step3:

In [8]:
nand_gate = logic_gate(-1,-1,2)
test(nand_gate)

0,0: 1.0
0,1: 1.0
1,0: 1.0
1,1: 0.0


## Part-III:

In [9]:
def xor_gate(a,b):
    c=or_gate(a,b)
    d=nand_gate(a,b)
    return and_gate(c,d)
test(xor_gate)

0,0: 0.0
0,1: 1.0
1,0: 1.0
1,1: 1.0


In [10]:
def logic_gate(w1, W2, b):
    return lambda x1, x2: sigmoid(w1 * x1 + W2 * x2 + b)
def final(gate):
    for a, b in zip(result1, result2):
        print("{}, {}: {}".format(a, b, np.round(gate(a, b))))
result1 = []
result2 = []
or_gate = logic_gate(20,20,-10)
for a, b in (0, 0), (0, 1), (1, 0), (1, 1):
    result1.append(np.round(or_gate(a,b)))
nand_gate = logic_gate(-23,-25,35)
for a, b in (0, 0), (0, 1), (1, 0), (1, 1):
    result2.append(np.round(nand_gate(a,b)))
xor_gate = logic_gate(20,20,-30)
print("XOR Gate truth table \n")
print("X, Y X+Y")
final(xor_gate)

XOR Gate truth table 

X, Y X+Y
0.0, 1.0: 0.0
1.0, 1.0: 1.0
1.0, 1.0: 1.0
1.0, 0.0: 0.0


### Part-IV: 

In [11]:
from tensorflow.keras.models import Sequential

In [12]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
#AND gate
# the four different states of the AND gate
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")
# the four expected results in the same order
target_data = np.array([[0],[0],[0],[1]], "float32")
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='mean_squared_error',
optimizer='adam',
metrics=['binary_accuracy'])
model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 0s - loss: 0.2424 - binary_accuracy: 0.7500 - 435ms/epoch - 435ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2418 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2411 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2404 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2397 - binary_accuracy: 0.7500 - 5ms/epoch - 5ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2391 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2384 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2377 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2371 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2364 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2357 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 12/100
1/1 - 0s - loss: 0.2351 - binary_accuracy: 0.7

Epoch 97/100
1/1 - 0s - loss: 0.1815 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 98/100
1/1 - 0s - loss: 0.1809 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 99/100
1/1 - 0s - loss: 0.1802 - binary_accuracy: 1.0000 - 4ms/epoch - 4ms/step
Epoch 100/100
1/1 - 0s - loss: 0.1796 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
1/1 [==============================] - 0s 79ms/step
[[0.]
 [0.]
 [0.]
 [1.]]


In [15]:
#OR gate
# the four different states of the OR gate
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")
# the four expected results in the same order
target_data = np.array([[0],[1],[1],[1]], "float32")
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='mean_squared_error',
optimizer='adam',
metrics=['binary_accuracy'])
model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 1s - loss: 0.2420 - binary_accuracy: 0.7500 - 507ms/epoch - 507ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2399 - binary_accuracy: 0.5000 - 2ms/epoch - 2ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2379 - binary_accuracy: 0.5000 - 2ms/epoch - 2ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2358 - binary_accuracy: 0.5000 - 4ms/epoch - 4ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2338 - binary_accuracy: 0.5000 - 2ms/epoch - 2ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2319 - binary_accuracy: 0.5000 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2299 - binary_accuracy: 0.5000 - 3ms/epoch - 3ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2280 - binary_accuracy: 0.5000 - 2ms/epoch - 2ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2261 - binary_accuracy: 0.5000 - 2ms/epoch - 2ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2242 - binary_accuracy: 0.5000 - 2ms/epoch - 2ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2224 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 12/100
1/1 - 0s - loss: 0.2206 - binary_accuracy: 0.7

Epoch 97/100
1/1 - 0s - loss: 0.1407 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 98/100
1/1 - 0s - loss: 0.1403 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 99/100
1/1 - 0s - loss: 0.1398 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 100/100
1/1 - 0s - loss: 0.1394 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
1/1 [==============================] - 0s 46ms/step
[[1.]
 [1.]
 [1.]
 [1.]]


In [16]:
#NOT gate
# the four different states of the NOT gate
training_data = np.array([[0],[1]], "float32")
# the four expected results in the same order
target_data = np.array([[1],[0]], "float32")
model = Sequential()
model.add(Dense(16, input_dim=1, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='mean_squared_error',
optimizer='adam',
metrics=['binary_accuracy'])
model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 1s - loss: 0.2464 - binary_accuracy: 0.5000 - 525ms/epoch - 525ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2459 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2454 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2449 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2444 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2440 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2435 - binary_accuracy: 1.0000 - 4ms/epoch - 4ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2430 - binary_accuracy: 1.0000 - 4ms/epoch - 4ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2425 - binary_accuracy: 1.0000 - 4ms/epoch - 4ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2421 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2416 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 12/100
1/1 - 0s - loss: 0.2412 - binary_accuracy: 1.0

Epoch 97/100
1/1 - 0s - loss: 0.2159 - binary_accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 98/100
1/1 - 0s - loss: 0.2157 - binary_accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 99/100
1/1 - 0s - loss: 0.2154 - binary_accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 100/100
1/1 - 0s - loss: 0.2152 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
1/1 [==============================] - 0s 46ms/step
[[1.]
 [0.]]


In [17]:
#NAND gate
# the four different states of the NAND gate
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")
# the four expected results in the same order
target_data = np.array([[1],[1],[1],[0]], "float32")
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='mean_squared_error',
optimizer='adam',
metrics=['binary_accuracy'])
model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 0s - loss: 0.2260 - binary_accuracy: 0.7500 - 461ms/epoch - 461ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2254 - binary_accuracy: 1.0000 - 1ms/epoch - 1ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2247 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2240 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2233 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2227 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2220 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2213 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2206 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2200 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2193 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 12/100
1/1 - 0s - loss: 0.2187 - binary_accuracy: 1.0

Epoch 97/100
1/1 - 0s - loss: 0.1565 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 98/100
1/1 - 0s - loss: 0.1558 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 99/100
1/1 - 0s - loss: 0.1550 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 100/100
1/1 - 0s - loss: 0.1543 - binary_accuracy: 1.0000 - 4ms/epoch - 4ms/step
1/1 [==============================] - 0s 49ms/step
[[1.]
 [1.]
 [1.]
 [0.]]


In [18]:
#NOR gate
# the four different states of the NOR gate
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")
# the four expected results in the same order
target_data = np.array([[1],[0],[0],[0]], "float32")
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='mean_squared_error',
optimizer='adam',
metrics=['binary_accuracy'])
model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 1s - loss: 0.1998 - binary_accuracy: 0.7500 - 678ms/epoch - 678ms/step
Epoch 2/100
1/1 - 0s - loss: 0.1986 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 3/100
1/1 - 0s - loss: 0.1974 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 4/100
1/1 - 0s - loss: 0.1962 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 5/100
1/1 - 0s - loss: 0.1949 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 6/100
1/1 - 0s - loss: 0.1938 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.1926 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 8/100
1/1 - 0s - loss: 0.1914 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 9/100
1/1 - 0s - loss: 0.1902 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 10/100
1/1 - 0s - loss: 0.1890 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 11/100
1/1 - 0s - loss: 0.1879 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 12/100
1/1 - 0s - loss: 0.1868 - binary_accuracy: 0.7

Epoch 97/100
1/1 - 0s - loss: 0.1284 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 98/100
1/1 - 0s - loss: 0.1280 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 99/100
1/1 - 0s - loss: 0.1276 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 100/100
1/1 - 0s - loss: 0.1272 - binary_accuracy: 0.7500 - 1000us/epoch - 1000us/step
1/1 [==============================] - 0s 53ms/step
[[0.]
 [0.]
 [0.]
 [0.]]


In [19]:
#XOR gate
# the four different states of the XOR gate
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")
# the four expected results in the same order
target_data = np.array([[0],[1],[1],[0]], "float32")
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='mean_squared_error',
optimizer='adam',
metrics=['binary_accuracy'])
model.fit(training_data, target_data, epochs=100, verbose=2)
print(model.predict(training_data).round())

Epoch 1/100
1/1 - 0s - loss: 0.2466 - binary_accuracy: 0.7500 - 450ms/epoch - 450ms/step
Epoch 2/100
1/1 - 0s - loss: 0.2463 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 3/100
1/1 - 0s - loss: 0.2460 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 4/100
1/1 - 0s - loss: 0.2457 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 5/100
1/1 - 0s - loss: 0.2454 - binary_accuracy: 0.7500 - 4ms/epoch - 4ms/step
Epoch 6/100
1/1 - 0s - loss: 0.2451 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 7/100
1/1 - 0s - loss: 0.2448 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 8/100
1/1 - 0s - loss: 0.2444 - binary_accuracy: 0.7500 - 2ms/epoch - 2ms/step
Epoch 9/100
1/1 - 0s - loss: 0.2441 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 10/100
1/1 - 0s - loss: 0.2438 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 11/100
1/1 - 0s - loss: 0.2435 - binary_accuracy: 0.7500 - 3ms/epoch - 3ms/step
Epoch 12/100
1/1 - 0s - loss: 0.2432 - binary_accuracy: 0.7

Epoch 97/100
1/1 - 0s - loss: 0.2180 - binary_accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 98/100
1/1 - 0s - loss: 0.2177 - binary_accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 99/100
1/1 - 0s - loss: 0.2173 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
Epoch 100/100
1/1 - 0s - loss: 0.2170 - binary_accuracy: 1.0000 - 3ms/epoch - 3ms/step
1/1 [==============================] - 0s 52ms/step
[[0.]
 [1.]
 [1.]
 [0.]]
